version: "3.9"

services:
  db:
    image: postgres:14.9
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5000:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
